# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Publish package to the Maven Central Repository

on:
  release:
    types: [ created ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

      - name: Build with Maven
        run: mvn -B package

      - name: Import GPG Key
        uses: actions/setup-java@v3
        with:
          java-version: '1.8'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Publish to Maven Central
        run: mvn -P sign-artifacts deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          CP_CLIENT_ID: ${{secrets.CP_CLIENT_ID}}
          CP_MERCHANT_ID: ${{secrets.CP_MERCHANT_ID}}
          CP_LICENCE_KEY: ${{secrets.CP_LICENCE_KEY}}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}